// Mock Data for LMS Stage 3
// This data simulates backend responses and will be used for CRUD operations

export const mockUsers = [
  {
    id: 'user-admin-1',
    username: 'admin',
    email: 'admin@lms.com',
    full_name: 'Admin User',
    role: 'admin',
    created_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 'user-mentor-1',
    username: 'john_doe',
    email: 'john.doe@lms.com',
    full_name: 'John Doe',
    role: 'mentor',
    department: 'Programming',
    specialization: 'React, Node.js, JavaScript',
    rating: 4.8,
    total_students: 250,
    total_courses: 5,
    status: 'active',
    created_at: '2024-01-15T00:00:00Z'
  },
  {
    id: 'user-mentor-2',
    username: 'jane_smith',
    email: 'jane.smith@lms.com',
    full_name: 'Jane Smith',
    role: 'mentor',
    department: 'Design',
    specialization: 'UI/UX, Figma, Design Systems',
    rating: 4.9,
    total_students: 180,
    total_courses: 3,
    status: 'active',
    created_at: '2024-01-20T00:00:00Z'
  },
  {
    id: 'user-mentor-3',
    username: 'mike_johnson',
    email: 'mike.johnson@lms.com',
    full_name: 'Mike Johnson',
    role: 'mentor',
    department: 'Data Science',
    specialization: 'Python, Machine Learning, Data Analysis',
    rating: 4.7,
    total_students: 220,
    total_courses: 4,
    status: 'active',
    created_at: '2024-02-01T00:00:00Z'
  },
  {
    id: 'user-mentor-4',
    username: 'sarah_williams',
    email: 'sarah.williams@lms.com',
    full_name: 'Sarah Williams',
    role: 'mentor',
    department: 'Business',
    specialization: 'Marketing, Strategy, Analytics',
    rating: 4.6,
    total_students: 95,
    total_courses: 2,
    status: 'on_leave',
    created_at: '2024-02-10T00:00:00Z'
  },
  {
    id: 'user-student-1',
    username: 'alice_brown',
    email: 'alice.brown@student.lms.com',
    full_name: 'Alice Brown',
    role: 'student',
    enrolled_courses: 3,
    completed_courses: 1,
    total_tasks: 15,
    completed_tasks: 12,
    attendance_percentage: 92,
    created_at: '2024-03-01T00:00:00Z'
  },
  {
    id: 'user-student-2',
    username: 'bob_wilson',
    email: 'bob.wilson@student.lms.com',
    full_name: 'Bob Wilson',
    role: 'student',
    enrolled_courses: 2,
    completed_courses: 0,
    total_tasks: 10,
    completed_tasks: 8,
    attendance_percentage: 88,
    created_at: '2024-03-05T00:00:00Z'
  },
  {
    id: 'user-student-3',
    username: 'carol_davis',
    email: 'carol.davis@student.lms.com',
    full_name: 'Carol Davis',
    role: 'student',
    enrolled_courses: 4,
    completed_courses: 2,
    total_tasks: 20,
    completed_tasks: 18,
    attendance_percentage: 95,
    created_at: '2024-03-10T00:00:00Z'
  },
  {
    id: 'user-student-4',
    username: 'david_moore',
    email: 'david.moore@student.lms.com',
    full_name: 'David Moore',
    role: 'student',
    enrolled_courses: 2,
    completed_courses: 1,
    total_tasks: 10,
    completed_tasks: 7,
    attendance_percentage: 85,
    created_at: '2024-03-15T00:00:00Z'
  },
  {
    id: 'user-student-5',
    username: 'emma_taylor',
    email: 'emma.taylor@student.lms.com',
    full_name: 'Emma Taylor',
    role: 'student',
    enrolled_courses: 3,
    completed_courses: 1,
    total_tasks: 15,
    completed_tasks: 14,
    attendance_percentage: 97,
    created_at: '2024-03-20T00:00:00Z'
  }
];

export const mockCourses = [
  {
    id: 'course-1',
    title: 'React Masterclass 2024',
    description: 'Master React from basics to advanced concepts including hooks, context, and performance optimization.',
    instructor_id: 'user-mentor-1',
    instructor_name: 'John Doe',
    category: 'Programming',
    level: 'Intermediate',
    duration: '8 weeks',
    total_students: 120,
    image: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    status: 'active',
    price: 299,
    rating: 4.8,
    total_lessons: 45,
    created_at: '2024-01-15T00:00:00Z'
  },
  {
    id: 'course-2',
    title: 'UI/UX Design Fundamentals',
    description: 'Learn the principles of user interface and user experience design with hands-on projects.',
    instructor_id: 'user-mentor-2',
    instructor_name: 'Jane Smith',
    category: 'Design',
    level: 'Beginner',
    duration: '6 weeks',
    total_students: 95,
    image: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    status: 'active',
    price: 249,
    rating: 4.9,
    total_lessons: 32,
    created_at: '2024-01-20T00:00:00Z'
  },
  {
    id: 'course-3',
    title: 'Python for Data Science',
    description: 'Comprehensive Python course covering data analysis, visualization, and machine learning basics.',
    instructor_id: 'user-mentor-3',
    instructor_name: 'Mike Johnson',
    category: 'Data Science',
    level: 'Intermediate',
    duration: '10 weeks',
    total_students: 150,
    image: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    status: 'active',
    price: 349,
    rating: 4.7,
    total_lessons: 52,
    created_at: '2024-02-01T00:00:00Z'
  },
  {
    id: 'course-4',
    title: 'Advanced JavaScript Patterns',
    description: 'Deep dive into JavaScript design patterns, async programming, and modern ES6+ features.',
    instructor_id: 'user-mentor-1',
    instructor_name: 'John Doe',
    category: 'Programming',
    level: 'Advanced',
    duration: '6 weeks',
    total_students: 85,
    image: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    status: 'active',
    price: 329,
    rating: 4.8,
    total_lessons: 38,
    created_at: '2024-02-10T00:00:00Z'
  },
  {
    id: 'course-5',
    title: 'Digital Marketing Strategy',
    description: 'Master digital marketing from SEO to social media marketing and content strategy.',
    instructor_id: 'user-mentor-4',
    instructor_name: 'Sarah Williams',
    category: 'Business',
    level: 'Beginner',
    duration: '8 weeks',
    total_students: 110,
    image: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
    status: 'pending_approval',
    price: 279,
    rating: 4.6,
    total_lessons: 40,
    created_at: '2024-02-15T00:00:00Z'
  },
  {
    id: 'course-6',
    title: 'Node.js Backend Development',
    description: 'Build scalable backend applications with Node.js, Express, and MongoDB.',
    instructor_id: 'user-mentor-1',
    instructor_name: 'John Doe',
    category: 'Programming',
    level: 'Intermediate',
    duration: '8 weeks',
    total_students: 102,
    image: 'linear-gradient(135deg, #30cfd0 0%, #330867 100%)',
    status: 'active',
    price: 319,
    rating: 4.7,
    total_lessons: 42,
    created_at: '2024-02-20T00:00:00Z'
  },
  {
    id: 'course-7',
    title: 'Figma for Designers',
    description: 'Complete guide to Figma including components, auto-layout, and prototyping.',
    instructor_id: 'user-mentor-2',
    instructor_name: 'Jane Smith',
    category: 'Design',
    level: 'Beginner',
    duration: '4 weeks',
    total_students: 78,
    image: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
    status: 'active',
    price: 199,
    rating: 4.9,
    total_lessons: 25,
    created_at: '2024-03-01T00:00:00Z'
  },
  {
    id: 'course-8',
    title: 'Machine Learning Fundamentals',
    description: 'Introduction to machine learning algorithms and their practical applications.',
    instructor_id: 'user-mentor-3',
    instructor_name: 'Mike Johnson',
    category: 'Data Science',
    level: 'Advanced',
    duration: '12 weeks',
    total_students: 92,
    image: 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)',
    status: 'draft',
    price: 399,
    rating: 4.8,
    total_lessons: 60,
    created_at: '2024-03-05T00:00:00Z'
  }
];

export const mockBatches = [
  {
    id: 'batch-1',
    name: 'React Masterclass - Batch A',
    course_id: 'course-1',
    course_name: 'React Masterclass 2024',
    mentor_id: 'user-mentor-1',
    mentor_name: 'John Doe',
    start_date: '2024-04-01',
    end_date: '2024-05-26',
    schedule: 'Mon, Wed, Fri - 6:00 PM to 8:00 PM',
    total_students: 45,
    status: 'active',
    created_at: '2024-03-15T00:00:00Z'
  },
  {
    id: 'batch-2',
    name: 'UI/UX Design - Evening Batch',
    course_id: 'course-2',
    course_name: 'UI/UX Design Fundamentals',
    mentor_id: 'user-mentor-2',
    mentor_name: 'Jane Smith',
    start_date: '2024-04-05',
    end_date: '2024-05-17',
    schedule: 'Tue, Thu - 7:00 PM to 9:00 PM',
    total_students: 32,
    status: 'active',
    created_at: '2024-03-18T00:00:00Z'
  },
  {
    id: 'batch-3',
    name: 'Python Data Science - Weekend',
    course_id: 'course-3',
    course_name: 'Python for Data Science',
    mentor_id: 'user-mentor-3',
    mentor_name: 'Mike Johnson',
    start_date: '2024-04-06',
    end_date: '2024-06-15',
    schedule: 'Sat, Sun - 10:00 AM to 1:00 PM',
    total_students: 38,
    status: 'active',
    created_at: '2024-03-20T00:00:00Z'
  },
  {
    id: 'batch-4',
    name: 'Advanced JS - Batch B',
    course_id: 'course-4',
    course_name: 'Advanced JavaScript Patterns',
    mentor_id: 'user-mentor-1',
    mentor_name: 'John Doe',
    start_date: '2024-05-01',
    end_date: '2024-06-12',
    schedule: 'Mon, Wed - 8:00 PM to 10:00 PM',
    total_students: 28,
    status: 'upcoming',
    created_at: '2024-03-25T00:00:00Z'
  }
];

export const mockAttendance = [
  {
    id: 'attend-1',
    batch_id: 'batch-1',
    batch_name: 'React Masterclass - Batch A',
    student_id: 'user-student-1',
    student_name: 'Alice Brown',
    date: '2024-04-01',
    status: 'present',
    marked_by: 'user-mentor-1',
    created_at: '2024-04-01T18:00:00Z'
  },
  {
    id: 'attend-2',
    batch_id: 'batch-1',
    batch_name: 'React Masterclass - Batch A',
    student_id: 'user-student-2',
    student_name: 'Bob Wilson',
    date: '2024-04-01',
    status: 'present',
    marked_by: 'user-mentor-1',
    created_at: '2024-04-01T18:00:00Z'
  },
  {
    id: 'attend-3',
    batch_id: 'batch-1',
    batch_name: 'React Masterclass - Batch A',
    student_id: 'user-student-1',
    student_name: 'Alice Brown',
    date: '2024-04-03',
    status: 'present',
    marked_by: 'user-mentor-1',
    created_at: '2024-04-03T18:00:00Z'
  },
  {
    id: 'attend-4',
    batch_id: 'batch-1',
    batch_name: 'React Masterclass - Batch A',
    student_id: 'user-student-2',
    student_name: 'Bob Wilson',
    date: '2024-04-03',
    status: 'absent',
    marked_by: 'user-mentor-1',
    created_at: '2024-04-03T18:00:00Z'
  },
  {
    id: 'attend-5',
    batch_id: 'batch-2',
    batch_name: 'UI/UX Design - Evening Batch',
    student_id: 'user-student-3',
    student_name: 'Carol Davis',
    date: '2024-04-05',
    status: 'present',
    marked_by: 'user-mentor-2',
    created_at: '2024-04-05T19:00:00Z'
  }
];

export const mockGrades = [
  {
    id: 'grade-1',
    course_id: 'course-1',
    course_name: 'React Masterclass 2024',
    student_id: 'user-student-1',
    student_name: 'Alice Brown',
    assessment_type: 'Assignment',
    assessment_name: 'React Hooks Project',
    score: 92,
    max_score: 100,
    grade: 'A',
    feedback: 'Excellent work on implementing custom hooks!',
    graded_by: 'user-mentor-1',
    graded_at: '2024-04-15T00:00:00Z'
  },
  {
    id: 'grade-2',
    course_id: 'course-1',
    course_name: 'React Masterclass 2024',
    student_id: 'user-student-2',
    student_name: 'Bob Wilson',
    assessment_type: 'Quiz',
    assessment_name: 'React Basics Quiz',
    score: 78,
    max_score: 100,
    grade: 'B',
    feedback: 'Good understanding. Work on component lifecycle.',
    graded_by: 'user-mentor-1',
    graded_at: '2024-04-10T00:00:00Z'
  },
  {
    id: 'grade-3',
    course_id: 'course-2',
    course_name: 'UI/UX Design Fundamentals',
    student_id: 'user-student-3',
    student_name: 'Carol Davis',
    assessment_type: 'Project',
    assessment_name: 'Mobile App Design',
    score: 95,
    max_score: 100,
    grade: 'A+',
    feedback: 'Outstanding design work with great attention to detail!',
    graded_by: 'user-mentor-2',
    graded_at: '2024-04-20T00:00:00Z'
  },
  {
    id: 'grade-4',
    course_id: 'course-3',
    course_name: 'Python for Data Science',
    student_id: 'user-student-1',
    student_name: 'Alice Brown',
    assessment_type: 'Assignment',
    assessment_name: 'Data Analysis Project',
    score: 88,
    max_score: 100,
    grade: 'A',
    feedback: 'Great analysis and visualization skills.',
    graded_by: 'user-mentor-3',
    graded_at: '2024-04-18T00:00:00Z'
  }
];

export const mockTasks = [
  {
    id: 'task-1',
    title: 'Build a Todo App with React Hooks',
    description: 'Create a fully functional todo application using React hooks (useState, useEffect, useContext). Include add, edit, delete, and mark complete functionality.',
    course_id: 'course-1',
    course_name: 'React Masterclass 2024',
    batch_id: 'batch-1',
    assigned_by: 'user-mentor-1',
    assigned_by_name: 'John Doe',
    due_date: '2024-04-20',
    status: 'active',
    total_submissions: 38,
    pending_submissions: 7,
    max_score: 100,
    created_at: '2024-04-05T00:00:00Z'
  },
  {
    id: 'task-2',
    title: 'Design a Landing Page Wireframe',
    description: 'Create a complete wireframe for a SaaS product landing page including hero section, features, testimonials, and CTA.',
    course_id: 'course-2',
    course_name: 'UI/UX Design Fundamentals',
    batch_id: 'batch-2',
    assigned_by: 'user-mentor-2',
    assigned_by_name: 'Jane Smith',
    due_date: '2024-04-25',
    status: 'active',
    total_submissions: 28,
    pending_submissions: 4,
    max_score: 100,
    created_at: '2024-04-08T00:00:00Z'
  },
  {
    id: 'task-3',
    title: 'Data Analysis with Pandas',
    description: 'Analyze the provided dataset using Pandas. Create visualizations and provide insights about the data trends.',
    course_id: 'course-3',
    course_name: 'Python for Data Science',
    batch_id: 'batch-3',
    assigned_by: 'user-mentor-3',
    assigned_by_name: 'Mike Johnson',
    due_date: '2024-04-22',
    status: 'active',
    total_submissions: 30,
    pending_submissions: 8,
    max_score: 100,
    created_at: '2024-04-06T00:00:00Z'
  },
  {
    id: 'task-4',
    title: 'Implement Async/Await Patterns',
    description: 'Create examples demonstrating proper use of async/await, Promise.all, and error handling in asynchronous JavaScript.',
    course_id: 'course-4',
    course_name: 'Advanced JavaScript Patterns',
    batch_id: 'batch-4',
    assigned_by: 'user-mentor-1',
    assigned_by_name: 'John Doe',
    due_date: '2024-05-10',
    status: 'upcoming',
    total_submissions: 0,
    pending_submissions: 0,
    max_score: 100,
    created_at: '2024-04-01T00:00:00Z'
  }
];

export const mockSubmissions = [
  {
    id: 'sub-1',
    task_id: 'task-1',
    task_title: 'Build a Todo App with React Hooks',
    student_id: 'user-student-1',
    student_name: 'Alice Brown',
    submission_url: 'https://github.com/alice/todo-app',
    submission_text: 'Implemented all required features with additional filtering options.',
    submitted_at: '2024-04-18T15:30:00Z',
    status: 'graded',
    score: 92,
    feedback: 'Excellent work! Clean code and good use of hooks.',
    graded_by: 'user-mentor-1',
    graded_at: '2024-04-19T10:00:00Z'
  },
  {
    id: 'sub-2',
    task_id: 'task-1',
    task_title: 'Build a Todo App with React Hooks',
    student_id: 'user-student-2',
    student_name: 'Bob Wilson',
    submission_url: 'https://github.com/bob/todo-react',
    submission_text: 'Todo app with basic functionality completed.',
    submitted_at: '2024-04-19T20:15:00Z',
    status: 'pending',
    score: null,
    feedback: null,
    graded_by: null,
    graded_at: null
  },
  {
    id: 'sub-3',
    task_id: 'task-2',
    task_title: 'Design a Landing Page Wireframe',
    student_id: 'user-student-3',
    student_name: 'Carol Davis',
    submission_url: 'https://figma.com/carol/landing-wireframe',
    submission_text: 'Complete wireframe with annotations and user flow.',
    submitted_at: '2024-04-23T14:00:00Z',
    status: 'graded',
    score: 95,
    feedback: 'Outstanding design! Great attention to detail.',
    graded_by: 'user-mentor-2',
    graded_at: '2024-04-24T09:30:00Z'
  }
];

export const mockEnrollments = [
  {
    id: 'enroll-1',
    student_id: 'user-student-1',
    student_name: 'Alice Brown',
    course_id: 'course-1',
    course_name: 'React Masterclass 2024',
    batch_id: 'batch-1',
    enrolled_at: '2024-03-28T00:00:00Z',
    progress: 65,
    status: 'active'
  },
  {
    id: 'enroll-2',
    student_id: 'user-student-1',
    student_name: 'Alice Brown',
    course_id: 'course-3',
    course_name: 'Python for Data Science',
    batch_id: 'batch-3',
    enrolled_at: '2024-04-02T00:00:00Z',
    progress: 42,
    status: 'active'
  },
  {
    id: 'enroll-3',
    student_id: 'user-student-2',
    student_name: 'Bob Wilson',
    course_id: 'course-1',
    course_name: 'React Masterclass 2024',
    batch_id: 'batch-1',
    enrolled_at: '2024-03-29T00:00:00Z',
    progress: 55,
    status: 'active'
  },
  {
    id: 'enroll-4',
    student_id: 'user-student-3',
    student_name: 'Carol Davis',
    course_id: 'course-2',
    course_name: 'UI/UX Design Fundamentals',
    batch_id: 'batch-2',
    enrolled_at: '2024-04-01T00:00:00Z',
    progress: 78,
    status: 'active'
  },
  {
    id: 'enroll-5',
    student_id: 'user-student-3',
    student_name: 'Carol Davis',
    course_id: 'course-1',
    course_name: 'React Masterclass 2024',
    batch_id: 'batch-1',
    enrolled_at: '2024-03-27T00:00:00Z',
    progress: 100,
    status: 'completed'
  }
];

export const mockCertificates = [
  {
    id: 'cert-1',
    student_id: 'user-student-3',
    student_name: 'Carol Davis',
    course_id: 'course-1',
    course_name: 'React Masterclass 2024',
    issued_date: '2024-05-30',
    certificate_url: '/certificates/cert-1.pdf',
    grade: 'A',
    final_score: 92
  },
  {
    id: 'cert-2',
    student_id: 'user-student-1',
    student_name: 'Alice Brown',
    course_id: 'course-6',
    course_name: 'Node.js Backend Development',
    issued_date: '2024-04-15',
    certificate_url: '/certificates/cert-2.pdf',
    grade: 'A+',
    final_score: 95
  }
];
